spring.application.name=lab4
spring.kafka.bootstrap-servers=broker1:29092,broker2:29093
spring.kafka.streams.application-id=lab4-streams
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.auto.offset.reset=earliest
spring.kafka.streams.auto-startup=true
logging.level.org.apache.kafka=INFO
logging.level.com.example.lab4=DEBUG
